# Environment settings
env:
  name: "sokoban"
  env_kwargs:
    dim_room: [6, 6]
    num_boxes: 1
    max_steps: 100
    search_depth: 30 # this will change the starting position of the player
    invalid_act: 0
    invalid_act_score: 0
