# @package _global_

defaults:
  - base

# Enable Archer algorithm
algorithm:
  experiment_name: archer-test
  trainer_type: archer  # Use 'archer' instead of default 'ppo'
  # Archer-specific parameters
  replay_buffer_capacity: 50000
  batch_size: 2
  gamma: 0.9
  tau: 0.005
  actor_lr: 3e-4
  critic_lr: 3e-4
  target_update_freq: 1

# es_manager:
#   format_penalty: -0.1
#   train:
#     env_groups: 2
#     # under the same group, the env config and env seed are ensured to be equal
#     group_size: 8
#     env_configs:
#       tags: ["SimpleSokoban"]
#       n_groups: [2] # If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation
#   val:
#     env_groups: 2
#     group_size: 1 # should be set to 1 because when val temperature is set to 0 and group size > 1, there will be repetitive prompts which leads to same trajectory.
#     env_configs:
#       tags: ["SimpleSokoban"]
#       n_groups: [2] # TODO: If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation
