# System settings
system:
  cuda_visible_devices: 0
  n_gpus: 1
  vllm_attention_backend: "XFORMERS"
  hydra_output_subdir: "outputs/exp_configs/logs/$(date +%Y-%m-%d)/$(date +%H-%M-%S)"

# Data configuration
data:
  train_files: "${env.data_dir}/train.parquet"
  val_files: "${env.data_dir}/test.parquet"
  train_data_num: null
  val_data_num: 50
  train_batch_size: 8
  val_batch_size: 10
  max_start_length: 400
  max_response_length: 400
  max_obs_length: 200
  shuffle: true

# Model configuration
model:
  path: "Qwen/Qwen2.5-0.5B-Instruct"
  enable_gradient_checkpointing: true

# Critic configuration
critic:
  ppo_micro_batch_size: 1
  model:
    path: null
  optim:
    lr: 1.0e-5
    
# Actor configuration
actor:
  use_kl_loss: true
  kl_loss_coef: 0.001
  kl_loss_type: "low_var_kl"
  ppo_mini_batch_size: 128
  ppo_micro_batch_size: 1
  state_masking: false
  optim:
    lr: 1.0e-6

# Rollout configuration
rollout:
  tensor_model_parallel_size: 1
  gpu_memory_utilization: 0.4
  n_agent: 16
  temperature: 0.7
  log_prob_micro_batch_size: 1

# Reference model configuration
ref:
  log_prob_micro_batch_size: 1

# Algorithm settings
algorithm:
  adv_estimator: "gae"
  kl_ctrl:
    kl_coef: 0.001
  no_think_rl: false

# Environment settings
env:
  name: "sokoban"  # This will be overridden by env-specific YAML
  data_dir: "data/sokoban"  # This will be overridden by env-specific YAML
  env_kwargs:
    # Environment-specific parameters will be defined in env-specific YAML

# Training settings
training:
  max_turns: 5
  total_epochs: 5
  total_training_steps: null
  ref_update_steps: null

# Logging settings
logging:
  mode: "['wandb']"
  log_images: true
  log_image_dir: "log/trajectory"
  log_image_step_size: 4
  log_n_image_per_batch: 32

# Trainer settings
trainer:
  val_before_train: true
  val_only: false
  default_hdfs_dir: null
  nnodes: 1
  save_freq: 100
  test_freq: 200
  project_name: "RAGEN"
  experiment_name: "ragen-main-exp"