env:
  name: "two_armed_bandit"
  data_dir: "data/two_armed_bandit"
  env_kwargs:
    low_risk_name_train: "phoenix"
    high_risk_name_train: "dragon"
    low_risk_name_val: "phoenix"
    high_risk_name_val: "dragon"

